services:
  - type: web
    name: orbit-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        value: orbit-secret-key-production-2025
      - key: DATABASE_URL
        value: postgres://postgres:postgres@postgres:5432/orbit_db
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*"
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true
